from __future__ import annotations

from concurrent.futures import ProcessPoolExecutor, as_completed
from datetime import datetime
import json
import os
from pathlib import Path
from typing import Any

import matplotlib.pyplot as plt
from matplotlib.colors import TwoSlopeNorm
import numpy as np
import pandas as pd

import analyze_qmt_roll_stage744_official_monthly_start_audit as s744
import analyze_qmt_roll_stage746_half_risk_no_streak_multiperiod as s746
import analyze_qmt_roll_stage660_stage653_multiperiod_live_audit as s660


PROJECT_DIR = Path(__file__).resolve().parent
OUTPUT_DIR = PROJECT_DIR / "backtest_outputs"

MODEL_TAG = "stage747_half_risk_no_streak_monthly_start_compare_v1"
OUTPUT_PREFIX = "qmt_roll_stage747_half_risk_no_streak_monthly_start_compare"
LINE_ID = "futures_trend_quarter_risk_no_streak"

ANALYSIS_END = s744.ANALYSIS_END
MONTH_STARTS = s744.MONTH_STARTS

SUMMARY_PATH = OUTPUT_DIR / f"{OUTPUT_PREFIX}_summary_{MODEL_TAG}.csv"
CANDIDATE_SUMMARY_PATH = OUTPUT_DIR / f"{OUTPUT_PREFIX}_candidate_summary_{MODEL_TAG}.csv"
COST_PATH = OUTPUT_DIR / f"{OUTPUT_PREFIX}_cost_stress_{MODEL_TAG}.csv"
COMPARISON_PATH = OUTPUT_DIR / f"{OUTPUT_PREFIX}_comparison_{MODEL_TAG}.csv"
CURVES_PATH = OUTPUT_DIR / f"{OUTPUT_PREFIX}_curves_{MODEL_TAG}.csv"
CHECKS_PATH = OUTPUT_DIR / f"{OUTPUT_PREFIX}_checks_{MODEL_TAG}.csv"
DECISION_PATH = OUTPUT_DIR / f"{OUTPUT_PREFIX}_decision_{MODEL_TAG}.json"
REPORT_PATH = OUTPUT_DIR / f"{OUTPUT_PREFIX}_report_{MODEL_TAG}.md"
CHART_PATH = OUTPUT_DIR / f"{OUTPUT_PREFIX}_chart_{MODEL_TAG}.png"
HEATMAP_PATH = OUTPUT_DIR / f"{OUTPUT_PREFIX}_heatmap_{MODEL_TAG}.png"

A_ARM = "A_official"
C_ARM = "C_r040_no_streak"
MAX_WORKERS = max(1, min(4, int(os.environ.get("STAGE747_MAX_WORKERS", "4"))))


def _json_safe(value: Any) -> Any:
    return s744._json_safe(value)


def _md_table(frame: pd.DataFrame, max_rows: int | None = None) -> str:
    return s744._md_table(frame, max_rows=max_rows)


def _require_official_inputs() -> None:
    for path in (s744.SUMMARY_PATH, s744.CURVES_PATH):
        if not path.exists():
            raise FileNotFoundError(f"missing Stage744 official monthly output: {path}")


def _window_name(start: pd.Timestamp) -> str:
    return f"mstart_{start.strftime('%Y_%m')}"


def _window_label(start: pd.Timestamp) -> str:
    return f"{start.strftime('%Y-%m')} independent start to {ANALYSIS_END.strftime('%Y-%m-%d')}"


def _add_month_fields(summary: pd.DataFrame) -> pd.DataFrame:
    frame = summary.copy()
    if "requested_start_month" in frame.columns:
        frame["start_month"] = frame["requested_start_month"].astype(str)
    else:
        frame["start_month"] = pd.to_datetime(frame["analysis_start"], errors="coerce").dt.to_period("M").astype(str)
    start_ts = pd.to_datetime(frame["start_month"] + "-01", errors="coerce")
    frame["start_year"] = start_ts.dt.year
    frame["start_month_num"] = start_ts.dt.month
    frame["positive_return"] = (pd.to_numeric(frame["rebased_total_return_pct"], errors="coerce") > 0.0).astype(int)
    frame["mature_63d"] = (pd.to_numeric(frame["trading_days"], errors="coerce") >= 63).astype(int)
    frame["mature_126d"] = (pd.to_numeric(frame["trading_days"], errors="coerce") >= 126).astype(int)
    frame["mature_252d"] = (pd.to_numeric(frame["trading_days"], errors="coerce") >= 252).astype(int)
    return frame


def _official_summary() -> pd.DataFrame:
    _require_official_inputs()
    frame = pd.read_csv(s744.SUMMARY_PATH, encoding="utf-8-sig")
    frame = frame[frame["window_group"].astype(str).eq("monthly_start")].copy()
    frame["arm"] = A_ARM
    frame["variant"] = s746.BASE_VARIANT
    return _add_month_fields(frame)


def _official_curves() -> pd.DataFrame:
    frame = pd.read_csv(s744.CURVES_PATH, encoding="utf-8-sig")
    frame["arm"] = A_ARM
    frame["variant"] = s746.BASE_VARIANT
    frame["start_month"] = frame["requested_start_month"].astype(str)
    return frame


def _run_candidate_month(
    start_iso: str,
    metadata: dict[str, Any],
    spec: s660.s653.ForcedVariant,
) -> tuple[dict[str, Any], list[dict[str, Any]], pd.DataFrame]:
    start = pd.Timestamp(start_iso)
    name = _window_name(start)
    frame, forced_events = s660._run_independent_window(
        spec=spec,
        metadata=metadata,
        analysis_start=start,
        analysis_end=ANALYSIS_END,
    )

    # s660._window_metrics filters forced events by the official variant name.
    # The events here are already generated by the candidate run, so normalize
    # the variant only for metric counting.
    forced_for_metrics = forced_events.copy()
    if not forced_for_metrics.empty:
        forced_for_metrics["variant"] = s660.OFFICIAL_LIVE_PROFILE_NAME

    summary, curve, costs = s660._window_metrics(
        frame,
        window_name=name,
        window_label=_window_label(start),
        group="monthly_start",
        source_name="stage747_half_risk_no_streak_monthly_start",
        caveat=(
            "fresh independent monthly start; Stage746 risk_multiplier=0.40; "
            "loss-streak throttle and recovery sleeve disabled"
        ),
        forced_events=forced_for_metrics,
    )
    summary["requested_start_month"] = start.strftime("%Y-%m")
    summary["arm"] = C_ARM
    summary["variant"] = s746.CANDIDATE_VARIANT

    curve["requested_start_month"] = start.strftime("%Y-%m")
    curve["start_month"] = start.strftime("%Y-%m")
    curve["arm"] = C_ARM
    curve["variant"] = s746.CANDIDATE_VARIANT

    for row in costs:
        row["requested_start_month"] = start.strftime("%Y-%m")
        row["start_month"] = start.strftime("%Y-%m")
        row["arm"] = C_ARM
        row["variant"] = s746.CANDIDATE_VARIANT
    return summary, costs, curve


def _run_candidate_monthly() -> tuple[pd.DataFrame, pd.DataFrame, pd.DataFrame]:
    metadata = s744.s513._metadata()
    spec = s746._candidate_spec(metadata)
    summary_rows: list[dict[str, Any]] = []
    cost_rows: list[dict[str, Any]] = []
    curve_frames: list[pd.DataFrame] = []

    start_items = [start.strftime("%Y-%m-%d") for start in MONTH_STARTS]
    print(f"[stage747] launching {len(start_items)} monthly starts with workers={MAX_WORKERS}", flush=True)
    if MAX_WORKERS == 1:
        for idx, start_iso in enumerate(start_items, start=1):
            print(f"[stage747] running {idx}/{len(start_items)} {_window_name(pd.Timestamp(start_iso))}", flush=True)
            summary, costs, curve = _run_candidate_month(start_iso, metadata, spec)
            summary_rows.append(summary)
            cost_rows.extend(costs)
            curve_frames.append(curve)
    else:
        with ProcessPoolExecutor(max_workers=MAX_WORKERS) as executor:
            futures = {executor.submit(_run_candidate_month, start_iso, metadata, spec): start_iso for start_iso in start_items}
            for idx, future in enumerate(as_completed(futures), start=1):
                start_iso = futures[future]
                summary, costs, curve = future.result()
                summary_rows.append(summary)
                cost_rows.extend(costs)
                curve_frames.append(curve)
                print(
                    f"[stage747] completed {idx}/{len(start_items)} {_window_name(pd.Timestamp(start_iso))}",
                    flush=True,
                )

    candidate = _add_month_fields(pd.DataFrame(summary_rows)).sort_values("start_month").reset_index(drop=True)
    cost = pd.DataFrame(cost_rows).sort_values(["start_month", "cost_multiplier"]).reset_index(drop=True)
    curves = (
        pd.concat(curve_frames, ignore_index=True, sort=False)
        .sort_values(["start_month", "date"])
        .reset_index(drop=True)
    )
    return candidate, cost, curves


def _build_comparison(official: pd.DataFrame, candidate: pd.DataFrame) -> pd.DataFrame:
    keep = [
        "start_month",
        "window_name",
        "analysis_start",
        "analysis_end",
        "trading_days",
        "rebased_end_equity",
        "rebased_total_return_pct",
        "rebased_cagr_pct",
        "rebased_max_dd_pct",
        "rebased_sharpe",
        "max_broker10_margin_to_rebased_equity_pct",
        "p95_broker10_margin_to_rebased_equity_pct",
        "days_over_100pct",
        "days_over_90pct",
        "total_slippage",
        "total_trade_count",
        "nonzero_daily_win_rate_pct",
        "forced_margin_deleverage_count",
        "forced_margin_deleverage_closed_volume",
        "deployable_pass",
        "mature_63d",
        "mature_126d",
        "mature_252d",
        "start_year",
        "start_month_num",
    ]
    left = official[keep].copy().add_prefix("a_")
    right = candidate[keep].copy().add_prefix("c_")
    merged = left.merge(right, left_on="a_start_month", right_on="c_start_month", how="inner")
    merged["start_month"] = merged["a_start_month"]
    merged["start_ts"] = pd.to_datetime(merged["start_month"] + "-01", errors="coerce")
    merged["start_year"] = merged["a_start_year"]
    merged["start_month_num"] = merged["a_start_month_num"]
    merged["trading_days"] = merged["a_trading_days"]
    merged["mature_63d"] = merged["a_mature_63d"]
    merged["mature_126d"] = merged["a_mature_126d"]
    merged["mature_252d"] = merged["a_mature_252d"]

    merged["return_delta_pct"] = merged["c_rebased_total_return_pct"] - merged["a_rebased_total_return_pct"]
    merged["end_equity_delta"] = merged["c_rebased_end_equity"] - merged["a_rebased_end_equity"]
    merged["return_retention_pct"] = np.where(
        merged["a_rebased_total_return_pct"].abs() > 1e-9,
        merged["c_rebased_total_return_pct"] / merged["a_rebased_total_return_pct"] * 100.0,
        np.nan,
    )
    merged["dd_delta_pp"] = merged["c_rebased_max_dd_pct"] - merged["a_rebased_max_dd_pct"]
    merged["sharpe_delta"] = merged["c_rebased_sharpe"] - merged["a_rebased_sharpe"]
    merged["margin_peak_delta_pp"] = (
        merged["c_max_broker10_margin_to_rebased_equity_pct"]
        - merged["a_max_broker10_margin_to_rebased_equity_pct"]
    )
    merged["trade_count_delta"] = merged["c_total_trade_count"] - merged["a_total_trade_count"]
    merged["slippage_delta"] = merged["c_total_slippage"] - merged["a_total_slippage"]
    merged["c_return_wins"] = (merged["return_delta_pct"] > 0.0).astype(int)
    merged["c_dd_wins"] = (merged["dd_delta_pp"] > 0.0).astype(int)
    merged["c_sharpe_wins"] = (merged["sharpe_delta"] > 0.0).astype(int)
    merged["c_both_return_dd_wins"] = (merged["c_return_wins"].eq(1) & merged["c_dd_wins"].eq(1)).astype(int)
    merged["a_both_return_dd_wins"] = (
        merged["return_delta_pct"].lt(0.0) & merged["dd_delta_pp"].lt(0.0)
    ).astype(int)
    merged["c_positive_return"] = (merged["c_rebased_total_return_pct"] > 0.0).astype(int)
    merged["a_positive_return"] = (merged["a_rebased_total_return_pct"] > 0.0).astype(int)
    merged["c_dd30_fail"] = (merged["c_rebased_max_dd_pct"] < -30.0).astype(int)
    merged["a_dd30_fail"] = (merged["a_rebased_max_dd_pct"] < -30.0).astype(int)
    merged["c_dd40_fail"] = (merged["c_rebased_max_dd_pct"] < -40.0).astype(int)
    merged["a_dd40_fail"] = (merged["a_rebased_max_dd_pct"] < -40.0).astype(int)
    return merged.sort_values("start_ts").reset_index(drop=True)


def _bucket_stats(label: str, frame: pd.DataFrame) -> dict[str, Any]:
    if frame.empty:
        return {
            "bucket": label,
            "start_count": 0,
            "c_return_win_count": 0,
            "c_dd_win_count": 0,
            "c_both_return_dd_win_count": 0,
            "a_both_return_dd_win_count": 0,
            "c_positive_count": 0,
            "a_positive_count": 0,
            "c_dd30_fail_count": 0,
            "a_dd30_fail_count": 0,
            "c_dd40_fail_count": 0,
            "a_dd40_fail_count": 0,
            "median_return_delta_pct": 0.0,
            "median_return_retention_pct": 0.0,
            "median_dd_delta_pp": 0.0,
            "worst_return_delta_start": "",
            "best_return_delta_start": "",
        }
    ret_delta = pd.to_numeric(frame["return_delta_pct"], errors="coerce")
    dd_delta = pd.to_numeric(frame["dd_delta_pp"], errors="coerce")
    retention = pd.to_numeric(frame["return_retention_pct"], errors="coerce")
    return {
        "bucket": label,
        "start_count": int(len(frame)),
        "c_return_win_count": int(frame["c_return_wins"].sum()),
        "c_return_win_rate_pct": float(frame["c_return_wins"].mean() * 100.0),
        "c_dd_win_count": int(frame["c_dd_wins"].sum()),
        "c_dd_win_rate_pct": float(frame["c_dd_wins"].mean() * 100.0),
        "c_both_return_dd_win_count": int(frame["c_both_return_dd_wins"].sum()),
        "a_both_return_dd_win_count": int(frame["a_both_return_dd_wins"].sum()),
        "c_positive_count": int(frame["c_positive_return"].sum()),
        "a_positive_count": int(frame["a_positive_return"].sum()),
        "c_dd30_fail_count": int(frame["c_dd30_fail"].sum()),
        "a_dd30_fail_count": int(frame["a_dd30_fail"].sum()),
        "c_dd40_fail_count": int(frame["c_dd40_fail"].sum()),
        "a_dd40_fail_count": int(frame["a_dd40_fail"].sum()),
        "median_return_delta_pct": float(ret_delta.median()),
        "p10_return_delta_pct": float(ret_delta.quantile(0.10)),
        "median_return_retention_pct": float(retention.median()),
        "median_dd_delta_pp": float(dd_delta.median()),
        "worst_dd_delta_pp": float(dd_delta.min()),
        "best_dd_delta_pp": float(dd_delta.max()),
        "worst_return_delta_start": str(frame.loc[ret_delta.idxmin(), "start_month"]),
        "best_return_delta_start": str(frame.loc[ret_delta.idxmax(), "start_month"]),
    }


def _checks(comparison: pd.DataFrame) -> pd.DataFrame:
    rows = [
        _bucket_stats("all_monthly_starts", comparison),
        _bucket_stats("mature_ge63_trading_days", comparison[comparison["mature_63d"].eq(1)]),
        _bucket_stats("mature_ge126_trading_days", comparison[comparison["mature_126d"].eq(1)]),
        _bucket_stats("mature_ge252_trading_days", comparison[comparison["mature_252d"].eq(1)]),
    ]
    for year, group in comparison.groupby("start_year", sort=True):
        rows.append(_bucket_stats(f"start_year_{int(year)}", group))
    return pd.DataFrame(rows)


def _decision(comparison: pd.DataFrame, checks: pd.DataFrame) -> dict[str, Any]:
    all_row = checks[checks["bucket"].eq("all_monthly_starts")].iloc[0]
    mature_row = checks[checks["bucket"].eq("mature_ge252_trading_days")].iloc[0]
    full = comparison[comparison["start_month"].eq("2020-01")].iloc[0]
    hard_fail: list[str] = []
    watch: list[str] = []
    if float(full["return_retention_pct"]) < 35.0:
        hard_fail.append("full_2020_01_return_retention_lt35")
    if int(full["c_dd30_fail"]) == 1:
        hard_fail.append("full_2020_01_c_dd30_fail")
    if int(mature_row["c_return_win_count"]) < int(mature_row["start_count"]) * 0.45:
        hard_fail.append("mature252_c_return_wins_lt45pct")
    if int(mature_row["c_dd30_fail_count"]) > int(mature_row["a_dd30_fail_count"]):
        watch.append("mature252_c_dd30_fail_more_than_official")
    if float(mature_row["median_return_delta_pct"]) < 0.0:
        hard_fail.append("mature252_median_return_delta_negative")
    if int(all_row["c_both_return_dd_win_count"]) <= int(all_row["a_both_return_dd_win_count"]):
        watch.append("all_c_both_wins_not_more_than_a_both_wins")
    decision = "half_risk_no_streak_monthly_start_not_promoted" if hard_fail else "half_risk_no_streak_monthly_start_watch"
    return {
        "stage": "Stage436",
        "script_stage": "Stage747",
        "line_id": LINE_ID,
        "model_tag": MODEL_TAG,
        "generated_at": datetime.now().strftime("%Y-%m-%d %H:%M:%S"),
        "baseline": s746.BASE_VARIANT,
        "candidate": s746.CANDIDATE_VARIANT,
        "analysis_start_first": MONTH_STARTS[0].strftime("%Y-%m-%d"),
        "analysis_start_last": MONTH_STARTS[-1].strftime("%Y-%m-%d"),
        "analysis_end": ANALYSIS_END.strftime("%Y-%m-%d"),
        "monthly_start_count": len(comparison),
        "decision": decision,
        "hard_fail_checks": hard_fail,
        "watch_checks": watch,
        "change": {
            "official_config_changed": False,
            "ctp_connected": False,
            "order_api_called": False,
            "official_results_reused_from_stage744": True,
            "risk_multiplier_before": s746.FORMAL_RISK_MULTIPLIER,
            "risk_multiplier_after": s746.HALF_FORMAL_RISK_MULTIPLIER,
            "streak_risk_multipliers_after": s746.NO_STREAK_MULTIPLIERS,
            "enable_streak_entry_structure_risk_recovery_after": False,
            "enable_recovery_sleeve_after": False,
        },
        "checks": checks.to_dict("records"),
        "full_2020_01": full.to_dict(),
        "outputs": {
            "summary": str(SUMMARY_PATH),
            "candidate_summary": str(CANDIDATE_SUMMARY_PATH),
            "cost": str(COST_PATH),
            "comparison": str(COMPARISON_PATH),
            "curves": str(CURVES_PATH),
            "checks": str(CHECKS_PATH),
            "report": str(REPORT_PATH),
            "chart": str(CHART_PATH),
            "heatmap": str(HEATMAP_PATH),
            "decision": str(DECISION_PATH),
        },
    }


def _plot_main(comparison: pd.DataFrame) -> None:
    data = comparison.sort_values("start_ts").copy()
    x = np.arange(len(data))
    labels = data["start_month"].tolist()
    tick_idx = [idx for idx, label in enumerate(labels) if label.endswith("-01") or idx == len(labels) - 1]

    fig, axes = plt.subplots(4, 1, figsize=(18, 14), sharex=True)
    ax_ret, ax_delta, ax_dd, ax_dd_delta = axes

    ax_ret.plot(x, data["a_rebased_total_return_pct"], color="#ea580c", linewidth=1.8, label="A official return")
    ax_ret.plot(x, data["c_rebased_total_return_pct"], color="#2563eb", linewidth=1.8, label="C 0.5x risk no-streak return")
    ax_ret.axhline(0.0, color="#111827", linewidth=0.8)
    ax_ret.set_ylabel("Total return %")
    ax_ret.set_title("Monthly independent starts to 2026-04-30: total return")
    ax_ret.grid(axis="y", alpha=0.25)
    ax_ret.legend(loc="upper right")

    colors = np.where(data["return_delta_pct"] >= 0.0, "#059669", "#dc2626")
    ax_delta.bar(x, data["return_delta_pct"], color=colors, alpha=0.88, width=0.82)
    ax_delta.axhline(0.0, color="#111827", linewidth=0.9)
    ax_delta.set_ylabel("C - A return pp")
    ax_delta.set_title("Return difference: green means C beats official")
    ax_delta.grid(axis="y", alpha=0.22)

    ax_dd.plot(x, data["a_rebased_max_dd_pct"], color="#ea580c", linewidth=1.7, label="A official max DD")
    ax_dd.plot(x, data["c_rebased_max_dd_pct"], color="#2563eb", linewidth=1.7, label="C max DD")
    ax_dd.axhline(-30.0, color="#f97316", linestyle="--", linewidth=0.9, label="DD -30%")
    ax_dd.axhline(-40.0, color="#dc2626", linestyle="--", linewidth=0.9, label="DD -40%")
    ax_dd.set_ylabel("Max DD %")
    ax_dd.set_title("Max drawdown by start month")
    ax_dd.grid(axis="y", alpha=0.25)
    ax_dd.legend(loc="lower right", ncol=2)

    dd_colors = np.where(data["dd_delta_pp"] >= 0.0, "#059669", "#dc2626")
    ax_dd_delta.bar(x, data["dd_delta_pp"], color=dd_colors, alpha=0.88, width=0.82)
    ax_dd_delta.axhline(0.0, color="#111827", linewidth=0.9)
    ax_dd_delta.set_ylabel("C - A DD pp")
    ax_dd_delta.set_title("Drawdown difference: green means C is shallower")
    ax_dd_delta.grid(axis="y", alpha=0.22)
    ax_dd_delta.set_xticks(tick_idx)
    ax_dd_delta.set_xticklabels([labels[i] for i in tick_idx], rotation=45, ha="right")

    full = data[data["start_month"].eq("2020-01")].iloc[0]
    fig.suptitle(
        (
            "Stage747 A official vs C half-risk no-streak monthly-start comparison | "
            f"2020-01 retention {full['return_retention_pct']:.1f}% | "
            f"C return wins {int(data['c_return_wins'].sum())}/{len(data)}, "
            f"C DD wins {int(data['c_dd_wins'].sum())}/{len(data)}"
        ),
        fontsize=15,
    )
    fig.tight_layout(rect=(0, 0, 1, 0.965))
    fig.savefig(CHART_PATH, dpi=170)
    plt.close(fig)


def _heat_values(comparison: pd.DataFrame, column: str) -> pd.DataFrame:
    return (
        comparison.pivot_table(index="start_year", columns="start_month_num", values=column, aggfunc="first")
        .sort_index()
        .reindex(columns=list(range(1, 13)))
    )


def _plot_heatmap(comparison: pd.DataFrame) -> None:
    ret = _heat_values(comparison, "return_delta_pct")
    dd = _heat_values(comparison, "dd_delta_pp")

    fig, axes = plt.subplots(2, 1, figsize=(17, 8.5))
    specs = [
        (axes[0], ret, "C - A total return (percentage points)", "Return pp", "{:.0f}"),
        (axes[1], dd, "C - A max drawdown (pp; positive = C shallower)", "DD pp", "{:.1f}"),
    ]
    for ax, table, title, cbar_label, fmt in specs:
        values = table.to_numpy(dtype=float)
        finite = values[np.isfinite(values)]
        if finite.size:
            limit = float(np.nanpercentile(np.abs(finite), 90))
            limit = max(limit, 1.0)
        else:
            limit = 1.0
        norm = TwoSlopeNorm(vmin=-limit, vcenter=0.0, vmax=limit)
        image = ax.imshow(values, aspect="auto", cmap="RdYlGn", norm=norm)
        ax.set_title(title)
        ax.set_yticks(np.arange(len(table.index)))
        ax.set_yticklabels([str(int(item)) for item in table.index])
        ax.set_xticks(np.arange(12))
        ax.set_xticklabels([str(i) for i in range(1, 13)])
        ax.set_xlabel("Start month")
        ax.set_ylabel("Start year")
        for y in range(values.shape[0]):
            for x in range(values.shape[1]):
                value = values[y, x]
                if not np.isfinite(value):
                    continue
                text_color = "white" if abs(value) > limit * 0.55 else "#111827"
                ax.text(x, y, fmt.format(value), ha="center", va="center", fontsize=8, color=text_color)
        fig.colorbar(image, ax=ax, fraction=0.018, pad=0.01, label=cbar_label)

    fig.suptitle("Stage747 monthly-start advantage heatmaps: green favors C, red favors official", fontsize=15)
    fig.tight_layout(rect=(0, 0, 1, 0.955))
    fig.savefig(HEATMAP_PATH, dpi=170)
    plt.close(fig)


def _write_report(
    summary: pd.DataFrame,
    candidate: pd.DataFrame,
    cost: pd.DataFrame,
    comparison: pd.DataFrame,
    checks: pd.DataFrame,
    decision: dict[str, Any],
) -> None:
    columns = [
        "start_month",
        "trading_days",
        "a_rebased_end_equity",
        "c_rebased_end_equity",
        "a_rebased_total_return_pct",
        "c_rebased_total_return_pct",
        "return_delta_pct",
        "return_retention_pct",
        "a_rebased_max_dd_pct",
        "c_rebased_max_dd_pct",
        "dd_delta_pp",
        "a_rebased_sharpe",
        "c_rebased_sharpe",
        "sharpe_delta",
        "a_total_trade_count",
        "c_total_trade_count",
        "trade_count_delta",
        "a_total_slippage",
        "c_total_slippage",
        "slippage_delta",
    ]
    worst_return = comparison.sort_values("return_delta_pct").head(15)
    best_return = comparison.sort_values("return_delta_pct", ascending=False).head(15)
    worst_dd = comparison.sort_values("dd_delta_pp").head(15)
    best_dd = comparison.sort_values("dd_delta_pp", ascending=False).head(15)
    lines = [
        "# Stage436 / Script747 C版逐月启动对比正式版",
        "",
        f"- 生成时间：`{datetime.now().strftime('%Y-%m-%d %H:%M CST')}`",
        f"- line_id：`{LINE_ID}`",
        f"- A：当前正式 Stage372/20w `{s746.BASE_VARIANT}`。",
        f"- C：Stage746 `{s746.CANDIDATE_VARIANT}`，风险倍率 `0.40`，关闭连败缩放与 recovery sleeve。",
        f"- 起点范围：`2020-01` 至 `{MONTH_STARTS[-1].strftime('%Y-%m')}`，共 `{len(comparison)}` 个逐月独立启动；统一终点 `{ANALYSIS_END.strftime('%Y-%m-%d')}`。",
        "- 正式版逐月结果复用 Stage744；C 版本阶段重新逐月回测。",
        "- 不修改正式配置、不连接 CTP、不调用下单。",
        "",
        "## 外部调研判断",
        "",
        "- 固定比例仓位资料强调：降低风险倍率会直接降低复利斜率，不一定按线性比例保留收益。",
        "- Walk-forward / 多起点资料强调：单一起点曲线容易误判路径依赖，逐月启动比较更适合验证候选是否稳健。",
        "- 本阶段不新增优化参数，只做启动月份扰动检验，因此不是用历史窗口调参。",
        "",
        "## 检查聚合",
        "",
        _md_table(checks, max_rows=30),
        "",
        "## 最伤收益的起点",
        "",
        _md_table(worst_return[columns], max_rows=15),
        "",
        "## C收益相对最好的起点",
        "",
        _md_table(best_return[columns], max_rows=15),
        "",
        "## C回撤相对最差的起点",
        "",
        _md_table(worst_dd[columns], max_rows=15),
        "",
        "## C回撤相对最好的起点",
        "",
        _md_table(best_dd[columns], max_rows=15),
        "",
        "## 全部月起点明细",
        "",
        _md_table(comparison[columns], max_rows=90),
        "",
        "## 决策",
        "",
        f"- 决策：`{decision['decision']}`",
        f"- hard_fail_checks：`{', '.join(decision['hard_fail_checks']) or '无'}`",
        f"- watch_checks：`{', '.join(decision['watch_checks']) or '无'}`",
        "",
        "## 输出",
        "",
        f"- chart：`{CHART_PATH}`",
        f"- heatmap：`{HEATMAP_PATH}`",
        f"- comparison：`{COMPARISON_PATH}`",
    ]
    REPORT_PATH.write_text("\n".join(lines) + "\n", encoding="utf-8")


def main() -> None:
    official = _official_summary()
    official_curves = _official_curves()
    candidate, cost, candidate_curves = _run_candidate_monthly()
    comparison = _build_comparison(official, candidate)
    checks = _checks(comparison)
    decision = _decision(comparison, checks)

    summary = pd.concat([official, candidate], ignore_index=True, sort=False)
    curves = pd.concat([official_curves, candidate_curves], ignore_index=True, sort=False)

    _plot_main(comparison)
    _plot_heatmap(comparison)
    _write_report(summary, candidate, cost, comparison, checks, decision)

    summary.to_csv(SUMMARY_PATH, index=False, encoding="utf-8-sig")
    candidate.to_csv(CANDIDATE_SUMMARY_PATH, index=False, encoding="utf-8-sig")
    cost.to_csv(COST_PATH, index=False, encoding="utf-8-sig")
    comparison.to_csv(COMPARISON_PATH, index=False, encoding="utf-8-sig")
    curves.to_csv(CURVES_PATH, index=False, encoding="utf-8-sig")
    checks.to_csv(CHECKS_PATH, index=False, encoding="utf-8-sig")
    DECISION_PATH.write_text(json.dumps(_json_safe(decision), ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
    print(json.dumps(_json_safe(decision), ensure_ascii=False, indent=2))


if __name__ == "__main__":
    main()
